---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: i want to debug first task result
    debug:
      msg: "{{myfirsttaskresult}}"

  - name: i want to install git
    apt:
      name: git
      state: present
    when: myfirsttaskresult.stderr== ""

  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: myfirsttaskresult.stderr !=""          