---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy file from master to nodes\
    copy:
      src: mycopyfile
      dest: /home/sanjay/mycopyfile
  - name: install webserver
    apt:
      name: apache2
      state: present    
  - name: copy index file into node side
    template:
         src: myindexfile.j2
         dest: /var/www/html/index.html    

  - name: download internet file 
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/sanjay/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes      
  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted    